### ISSUE TITLE
error after running npm start

### ISSUE THREAD

**Issue by mylastore** [me-io/angular-6-starter#9]
I get this error when I run npm start.

`[HPM] Error occurred while trying to proxy request /api/posts?page=1 from localhost:4500 to http://localhost:3500 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/tags?q= from localhost:4500 to http://localhost:3500 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
`

ALSO THIS

`** Angular Live Development Server is listening on localhost:4500, open your browser on http://localhost:4500/ **
 10% building modules 3/3 modules 0 active[HPM] Proxy created: /api  ->  http://localhost:3500
**[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]**   `

**Comment by ziishaned** [comment]
Hey,

The first error is being thrown because you haven't set the API yet. Configure your [proxy.conf.js](https://github.com/me-io/angular-6-starter/blob/master/proxy.conf.js#L3) to point to your API URL. For example, you may clone [me-io/slim-api](https://github.com/me-io/slim-api) and set it up for use in your application. The second one is just the message that angular has started.

**Comment by mylastore** [comment]
so the signup and login needs the API also?

**Comment by ziishaned** [comment]
Yes
